'use strict';
const lessons = [
 {group:'01 · Meet Wizbot',title:'Ready, set, robot',intro:'Meet your robot and give it power before you start your first adventure.',steps:['Slide open the battery cover underneath. Insert three AAA batteries, matching the + and − marks. The flat minus end touches the metal spring. Close the cover until it clicks.','Find the nine command buttons and two LED lights on top. Underneath are two drive wheels, a caster wheel, a buzzer, two IR sensors and the three-way power switch.','Slide the switch to the middle for button coding. The other positions turn power off or select Picto-Coding. Use a flat, clear surface for your first moves.'],note:'Replace all three batteries together with fresh batteries of the same brand when the low-battery red light appears. Red lights also appear during calibration.',mission:'Find CLEAR, FORWARD and GO on the real robot. Point to its wheels and power switch.',question:'Which battery end touches the spring?',answers:['The flat minus (−) end','The plus (+) end','Either end'],correct:0,explanation:'The flat minus end goes against the spring; also match the compartment’s polarity marks.'},
 {group:'01 · Meet Wizbot',title:'One move at a time',intro:'A program is a list of instructions. Wizbot waits until GO before following your list.',steps:['Put Wizbot down facing the direction you want to travel. Press CLEAR to remove the previous program.','Tap FORWARD once, then press GO. Watch the distance it moves.','CLEAR again. Tap FORWARD twice, then GO. Compare the two journeys. REVERSE moves back without turning the robot.'],note:'The printed dots are a counting guide. Their spacing is not guaranteed to equal a real robot step.',mission:'In the playground, add Forward twice and press GO. Then CLEAR and try Reverse once.',demo:['F','F'],mode:'grid',question:'What starts the queued program?',answers:['FORWARD','GO','CLEAR'],correct:1,explanation:'GO runs the stored commands. CLEAR removes them.'},
 {group:'02 · Button coding',title:'Turn, then travel',intro:'A turn changes which way Wizbot faces. It does not take a step.',steps:['In Grid Mode, LEFT and RIGHT rotate the robot 90° on the spot. FORWARD then moves in its new direction.','Queue CLEAR → FORWARD → RIGHT → FORWARD → GO. Predict the destination before running it.','Use ACTION to add light and sound effects to a program. Try it at the end of your route.'],mission:'Reach the gold star in the playground. Start facing up; travel one square up, then one square right.',demo:['F','R','F'],mode:'grid',goal:[350,450],question:'After RIGHT, what must you tap to travel in the new direction?',answers:['FORWARD','CLEAR','RIGHT again'],correct:0,explanation:'RIGHT changes direction; FORWARD moves along that direction.'},
 {group:'02 · Button coding',title:'Treasure-land mission',intro:'Combine small moves into a longer route, then check each part.',steps:['Imagine visiting a friend on the hill before going to the beach. Point out the planned route before adding commands.','The supplied manual’s example is CLEAR → FORWARD → RIGHT → FORWARD → LEFT → FORWARD → RIGHT → FORWARD → FORWARD → ACTION → GO.','Run it in the playground. Watch each step. If your real arena has obstacles, check its layout before using the same sequence.'],note:'The playground shows a sample destination, not the original Treasure Land arena. Avoid obstacles on your own mat.',mission:'Reach the star at the end of the sample route. Build the sequence yourself, or load the example and explain every move.',demo:['F','R','F','L','F','R','F','F','A'],mode:'grid',goal:[450,400],question:'You want to replace an old program. What comes first?',answers:['GO','ACTION','CLEAR'],correct:2,explanation:'CLEAR removes old commands so they do not become part of the next journey.'},
 {group:'03 · Shapes & movement',title:'Choose a movement mode',intro:'Grid Mode is useful for square-by-square journeys. Draw Mode gives you shorter steps, angles and curves.',steps:['Press ACTION + REVERSE together to toggle Grid and Draw modes. Purple indicates Draw Mode.','To check Grid Mode by movement, CLEAR → FORWARD → RIGHT → GO. Grid Mode takes a full grid step and a 90° turn; Draw Mode takes a shorter step and turns on its central axis.','Use Grid for right-angled routes and Draw for finer shape movement. You can follow paths by moving the robot without attaching anything.'],note:'The supplied sources describe orange for button/grid operation, but also blue after toggling to Grid. Blue is additionally used for Picto-Coding. Check the switch and movement rather than relying on blue alone.',mission:'Run the same Forward → Right → Forward program in both playground modes. Compare the step lengths.',demo:['F','R','F'],mode:'draw',question:'Which mode supports angled turns and arcs?',answers:['Draw Mode','Power off','Grid Mode only'],correct:0,explanation:'Draw Mode adds angle shortcuts and curved movement.'},
 {group:'03 · Shapes & movement',title:'Angles and letter paths',intro:'Use smaller turns to explore diagonals and numbers on your path sheet.',steps:['In Draw Mode, press FORWARD + LEFT or RIGHT together to queue a 45° turn in that direction.','Press REVERSE + LEFT or RIGHT together to queue a 30° turn. Press GO after entering the whole plan.','Try the workbook’s L route: CLEAR → FORWARD → LEFT → FORWARD → GO. Its T route is FORWARD twice → REVERSE → RIGHT → FORWARD twice.','For a diagonal route, try FORWARD → RIGHT 45° → FORWARD. Match the starting direction to your printed path and adjust the plan as you observe.'],mission:'Load the diagonal example. Replace the 45° turn with a 30° turn and compare the paths.',demo:['F','R45','F'],mode:'draw',question:'What queues a 45° right turn on the real robot?',answers:['REVERSE + RIGHT','FORWARD + RIGHT','ACTION + RIGHT'],correct:1,explanation:'FORWARD + RIGHT queues 45°. REVERSE + RIGHT queues 30°. ACTION + RIGHT enters calibration.'},
 {group:'03 · Shapes & movement',title:'Curves, circles and hearts',intro:'An arc is part of a curve. Connect arcs to make a closed path.',steps:['In Draw Mode, hold LEFT or RIGHT for 1 second until a short chime to queue a small arc.','Hold LEFT or RIGHT for 3 seconds until a double chime to queue a wide arc. Then press GO.','For the manual’s circle: CLEAR → four small right arcs → GO.','The manual’s heart sequence is FORWARD twice → two wide right arcs → LEFT → two wide right arcs → FORWARD twice. Try it on an open surface and observe the result.'],note:'The simulator uses illustrative 90° arcs with two radii. Real arc distance and the heart’s geometry depend on the robot’s settings. A long FORWARD press (2 seconds, then GO) enables continuous motion on the real robot; use open space and be ready to switch power off.',mission:'Make a circle using four small right arcs. Predict whether Wizbot will return to its starting direction.',demo:['AR','AR','AR','AR'],mode:'draw',question:'What is the small-arc hold time?',answers:['1 second','3 seconds','10 seconds'],correct:0,explanation:'A one-second hold and a short chime queue a small arc; a three-second hold queues a wide arc.'},
 {group:'03 · Shapes & movement',title:'Loops: say it once',intro:'A loop repeats a set of instructions. It saves you entering the same pattern again and again.',steps:['On the real robot: CLEAR → REPEAT once to begin recording → enter the movement sequence → press REPEAT for the desired repetition count → GO.','The manual’s square example records FORWARD → RIGHT and repeats it four times.','In this playground, add Forward and Right, set Repeat sequence to 4, then GO. The repeat input represents the idea of a loop rather than the physical REPEAT button protocol.'],mission:'Create a square in Grid Mode. Change the repeat count to 3: what part is missing?',demo:['F','R'],mode:'grid',repeat:4,question:'How often must Forward → Right repeat to make a four-sided square?',answers:['2 times','3 times','4 times'],correct:2,explanation:'Four sides and four 90° turns bring the robot back to its starting pose.'},
 {group:'04 · Advanced adventures',title:'Follow a track & interrupt',intro:'Wizbot’s sensors can respond to a black track instead of following only your button plan.',steps:['The two IR sensors underneath compare reflected light from black and white surfaces.','For line following, long-press INTERRUPT until the continuous buzzer chime. Place Wizbot on a suitable black-line track and press GO.','The workbook describes an INTERRUPT in a main sequence, followed by urgent task commands: detecting a black strip triggers a task before the main routine resumes. Practise this using your robot’s track and command guide.','For the paper claw accessory, fold its marked lines, align its tabs with the front LED holes and secure with a rubber band as described in the manual.'],note:'The dashed, overlapping A4 paths are for manually coded movement. They are not a continuous sensor track. The playground does not simulate IR sensing or interruption.',mission:'Compare a solid black track and the dotted sheet. Explain why the sensors need a clear track.',question:'Which surface is intended for automatic line following?',answers:['The overlapping dashed sheet','A suitable continuous black-line track','Any coloured picture'],correct:1,explanation:'Line following needs a track the IR sensors can distinguish from the background.'},
 {group:'04 · Advanced adventures',title:'Build with visual blocks',intro:'Move from physical buttons to puzzle-shaped commands in Junior Blocks.',steps:['Select the Picto-Coding position on the power switch. The blue light indicates Bluetooth operation. Enable Bluetooth on your device.','In Junior Blocks, open Board → Wizbot Maxx, then choose your robot’s unique Bluetooth ID. Listen for the connection chime.','Build a horizontal sequence using Forward step, Reverse step, Left turn and Right turn blocks. Use the green flag or Run control in the app to execute it.','Explore Set LED, LED off, Play Sound, Stop Robot and loops. Use the Wizbot interface to select Grid or Draw movement.'],note:'This page is a course and simulator. Bluetooth pairing and real robot execution take place in Junior Blocks / PictoBlocks, not in this browser playground.',mission:'Plan Forward → Right → Forward → Action in the playground, then recreate it with movement and sound/light blocks in Junior Blocks.',demo:['F','R','F','A'],mode:'grid',question:'How do you know the selected robot has connected?',answers:['A connection chime sounds','The batteries fall out','CLEAR changes its ID'],correct:0,explanation:'The guide describes a chime when Bluetooth pairing succeeds.'},
 {group:'04 · Advanced adventures',title:'Tune movement and sensors',intro:'Calibration helps steps, turns and sensors behave more consistently.',steps:['Start in purple Draw Mode with wheels aligned to reference guidelines. ACTION + FORWARD enters step calibration; LEDs glow red and the robot takes a step. LEFT shortens the step, RIGHT lengthens it. FORWARD tests again; GO saves forward and reverse calibration.','ACTION + RIGHT or ACTION + LEFT enters that turn’s calibration. FORWARD increases the angle; REVERSE decreases it. Press the chosen turn again to test; GO saves.','On the proper black-and-white IR calibration track, align wheels on its white guidelines and press INTERRUPT + ACTION. Wizbot moves forward–reverse–forward to sample reflection.','In Junior Blocks: Board → Wizbot Settings → Calibrate Motion Time. Adjust the movement timing in milliseconds and choose Set. The guide compares 1500 ms with 1300 ms; these are examples, not universal settings.'],note:'Check fresh batteries and a flat surface before calibration. Change one setting at a time and compare with the same reference. Use the actual IR calibration track, not the dashed A4 sheet.',mission:'Choose a symptom: steps too long, turns too small, or track detection unreliable. Identify the matching calibration procedure.',question:'In forward-step calibration, which button shortens the step?',answers:['RIGHT','LEFT','GO'],correct:1,explanation:'LEFT shortens; RIGHT lengthens. GO saves the setting.'},
 {group:'05 · Final mission',title:'Plan your own adventure',intro:'Use what you know to make, test and improve a route of your own.',steps:['Open the printable path sheet. Choose circle, triangle, 1, 4 or 7. Identify its dash pattern and your starting direction.','Choose Grid or Draw Mode. Start with a short section, plan the moves, CLEAR, enter them and GO.','Count the dot gaps using the border numbers. Measure how far your robot really travels before assuming one gap equals one step.','Watch what happens at turns and crossings. Keep following the same pattern, revise your program and try a longer section.'],mission:'Build your own route in the playground, then try a short section on the robot. Explain one change that improved your result.',demo:['F','R45','F','L45','F'],mode:'draw',question:'The real robot misses the printed line. What is a useful next step?',answers:['Keep repeating the same plan without watching','Observe, adjust the start or commands, and test again','Assume every printed gap is one robot step'],correct:1,explanation:'Observe and improve. Real step lengths depend on mode, surface and calibration.'}
];
const $ = (id) => document.getElementById(id);
const storageKey='wizbot-academy-v1';
let saved={completed:[],current:0}, storageAvailable=true;
try { const value=JSON.parse(localStorage.getItem(storageKey)||'null'); if(value&&Array.isArray(value.completed))saved={completed:value.completed.filter(n=>Number.isInteger(n)&&n>=0&&n<lessons.length),current:Number.isInteger(value.current)&&value.current>=0&&value.current<lessons.length?value.current:0}; } catch {storageAvailable=false;}
let current=saved.current, passed=false;
function save(){saved.current=current;try{localStorage.setItem(storageKey,JSON.stringify(saved));}catch{storageAvailable=false;}$('storage-note').textContent=storageAvailable?'Progress is saved in this browser.':'Progress is available for this visit; browser storage is unavailable.';}
function renderNav(){let group='';$('lesson-nav').innerHTML=lessons.map((l,i)=>{const label=l.group!==group?`<p class="nav-group">${l.group}</p>`:'';group=l.group;return `${label}<button data-lesson="${i}" aria-current="${i===current}"><span class="lesson-number">${saved.completed.includes(i)?'✓':i+1}</span>${l.title}</button>`;}).join('');$('progress').value=saved.completed.length;$('progress-count').textContent=`${saved.completed.length} / ${lessons.length}`;$('resume').textContent=saved.completed.length===lessons.length?'Review your course →':saved.completed.length||current?'Continue learning →':'Start learning →';}
function showLesson(index,focus=false){current=index;passed=saved.completed.includes(index);const l=lessons[index];$('lesson').innerHTML=`<p class="lesson-tag">${l.group} · LESSON ${index+1} OF ${lessons.length}</p><h2>${l.title}</h2><p class="intro">${l.intro}</p><ol class="lesson-steps">${l.steps.map(s=>`<li>${s}</li>`).join('')}</ol>${l.note?`<div class="callout">${l.note}</div>`:''}<div class="mission"><p class="eyebrow">YOUR MISSION</p><p>${l.mission}</p>${l.demo?'<button id="load-demo">Try in the playground ↓</button>':''}${index===11?'<p><a href="a4sheet.html">Open printable path sheet ↗</a></p>':''}</div><section class="quiz" aria-label="Lesson check"><h3>Check your understanding</h3><p>${l.question}</p><div class="quiz-options">${l.answers.map((a,i)=>`<button data-answer="${i}">${a}</button>`).join('')}</div><p class="feedback" id="quiz-feedback" role="status">${passed?'You have completed this lesson. You can review the check anytime.':''}</p></section><div class="lesson-bottom"><button id="previous" ${index===0?'disabled':''}>← Previous</button><button id="complete" class="primary" ${passed?'':'disabled'}>${saved.completed.includes(index)?'Completed ✓':'Complete lesson ✓'}</button><button id="next" ${index===lessons.length-1?'disabled':''}>Next →</button></div>`;renderNav();save();if(focus)$('lesson').focus({preventScroll:true});}
$('lesson-nav').addEventListener('click',e=>{const b=e.target.closest('[data-lesson]');if(b)showLesson(Number(b.dataset.lesson),true);});
$('resume').addEventListener('click',()=>{$('course').scrollIntoView();$('lesson').focus({preventScroll:true});});
$('reset-progress').addEventListener('click',()=>{if(confirm('Reset all completed lessons in this browser?')){saved={completed:[],current:0};showLesson(0);}});
$('lesson').addEventListener('click',e=>{const answer=e.target.closest('[data-answer]');if(answer){const right=Number(answer.dataset.answer)===lessons[current].correct;answer.classList.add(right?'correct':'incorrect');$('quiz-feedback').textContent=right?`Yes! ${lessons[current].explanation}`:'Try again. Look back at the lesson steps.';if(right){passed=true;$('complete').disabled=false;}return;}if(e.target.id==='previous')showLesson(current-1,true);if(e.target.id==='next')showLesson(current+1,true);if(e.target.id==='complete'&&passed){if(!saved.completed.includes(current))saved.completed.push(current);save();renderNav();$('complete').textContent='Completed ✓';$('quiz-feedback').textContent=saved.completed.length===lessons.length?'Course complete! Keep experimenting with your own routes.':'Lesson saved. Continue when you are ready.';}if(e.target.id==='load-demo')loadDemo(lessons[current]);});
const commands={F:{label:'▲ Forward',mode:'both'},B:{label:'▼ Reverse',mode:'both'},L:{label:'◀ Left 90°',mode:'both'},R:{label:'▶ Right 90°',mode:'both'},A:{label:'✦ Action',mode:'both'},L45:{label:'↖ Left 45°',mode:'draw'},R45:{label:'↗ Right 45°',mode:'draw'},L30:{label:'↖ Left 30°',mode:'draw'},R30:{label:'↗ Right 30°',mode:'draw'},AL:{label:'◜ Small left arc',mode:'draw'},AR:{label:'◝ Small right arc',mode:'draw'},WL:{label:'◜ Wide left arc',mode:'draw'},WR:{label:'◝ Wide right arc',mode:'draw'}};
let queue=[],running=false,runToken=0,pose={x:300,y:500,a:0},trail='',goal=null;
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
function renderCommands(){$('command-buttons').innerHTML=Object.entries(commands).filter(([,c])=>c.mode==='both'||$('mode').value==='draw').map(([key,c])=>`<button data-command="${key}" ${running?'disabled':''}>${c.label}</button>`).join('');}
function renderQueue(){$('queue').innerHTML=queue.length?queue.map(c=>`<li>${commands[c].label}</li>`).join(''):'<li class="empty">No moves yet. Add your first command.</li>';$('undo').disabled=running||!queue.length;$('go').disabled=running||!queue.length;$('mode').disabled=running;$('repeat-count').disabled=running;renderCommands();}
function drawBot(){$('bot').setAttribute('transform',`translate(${pose.x} ${pose.y}) rotate(${pose.a})`);$('trail').setAttribute('d',trail);}
function resetPose(){pose={x:300,y:500,a:0};trail='M300 500';drawBot();}
function cancel(){runToken++;running=false;renderQueue();}
function renderGoal(){$('goal').innerHTML=goal?`<text x="${goal[0]}" y="${goal[1]+12}" text-anchor="middle" font-size="34" fill="#d79925">★</text>`:'';}
function loadDemo(l){cancel();queue=[...l.demo];$('mode').value=l.mode;$('repeat-count').value=l.repeat||1;goal=l.goal||null;renderGoal();resetPose();renderQueue();$('sim-status').textContent='Example loaded. Predict the path, then press GO.';$('lab').scrollIntoView();$('go').focus({preventScroll:true});}
$('command-buttons').addEventListener('click',e=>{const b=e.target.closest('[data-command]');if(b&&!running){if(queue.length>=64){$('sim-status').textContent='This practice program is limited to 64 commands.';return;}queue.push(b.dataset.command);renderQueue();}});
$('clear').addEventListener('click',()=>{cancel();queue=[];goal=null;renderGoal();resetPose();renderQueue();$('sim-status').textContent='Cleared. Facing up. Add moves, then press GO.';});
$('undo').addEventListener('click',()=>{if(!running){queue.pop();renderQueue();}});
$('stop').addEventListener('click',()=>{cancel();$('sim-status').textContent='Stopped. GO restarts the stored sequence from the starting point.';});
$('mode').addEventListener('change',()=>{cancel();queue=[];goal=null;renderGoal();resetPose();renderQueue();$('sim-status').textContent='Mode changed. Program cleared so you can compare movement.';});
async function execute(c,token){const radians=a=>a*Math.PI/180;if(['L','R','L45','R45','L30','R30'].includes(c)){pose.a+=(c.startsWith('L')?-1:1)*(c.includes('45')?45:c.includes('30')?30:90);drawBot();return true;}if(c==='A'){$('bot').querySelector('circle').setAttribute('fill','#b4a5ee');await delay(180);$('bot').querySelector('circle').setAttribute('fill','#ffc968');return token===runToken;}const step=$('mode').value==='grid'?50:25;const arc=['AL','AR','WL','WR'].includes(c);const start={...pose};const sign=c.endsWith('L')?-1:1;const radius=c.startsWith('W')?50:25;const cx=start.x+sign*radius*Math.cos(radians(start.a));const cy=start.y+sign*radius*Math.sin(radians(start.a));for(let i=1;i<=10;i++){if(token!==runToken)return false;let x,y,a=start.a;if(arc){a=start.a+sign*90*i/10;x=cx-sign*radius*Math.cos(radians(a));y=cy-sign*radius*Math.sin(radians(a));}else{const dist=(c==='B'?-1:1)*step*i/10;x=start.x+Math.sin(radians(a))*dist;y=start.y-Math.cos(radians(a))*dist;}if(x<22||x>578||y<22||y>578){$('sim-status').textContent='Edge reached. Shorten the route or change direction and try again.';return false;}pose={x,y,a};trail+=` L${x.toFixed(2)} ${y.toFixed(2)}`;drawBot();await delay(20);}return true;}
$('go').addEventListener('click',async()=>{if(running||!queue.length)return;let count=Number($('repeat-count').value);if(!Number.isInteger(count)||count<1||count>8){$('sim-status').textContent='Choose a whole-number repeat count from 1 to 8.';return;}running=true;const token=++runToken;resetPose();renderQueue();const program=Array.from({length:count},()=>queue).flat();for(let i=0;i<program.length;i++){if(token!==runToken)return;$('sim-status').textContent=`Move ${i+1} of ${program.length}: ${commands[program[i]].label}`;if(!await execute(program[i],token)){if(token===runToken){running=false;renderQueue();}return;}await delay(150);}if(token!==runToken)return;running=false;renderQueue();const reached=goal&&Math.hypot(pose.x-goal[0],pose.y-goal[1])<12;$('sim-status').textContent=goal?(reached?'Star reached! Explain why your plan worked.':'Finished. The star is still waiting—adjust your program and try again.'):`Finished ${program.length} commands. Facing ${((pose.a%360)+360)%360}° clockwise from up. Compare with your prediction.`;});
const reference=[
 ['Power & batteries','Setup','Three AAA batteries; flat minus ends against springs. Middle switch position: button coding. Replace all three batteries together when low.'],
 ['CLEAR, GO & ACTION','Buttons','CLEAR wipes memory. Enter commands in order, then GO executes them. ACTION adds light and sound effects.'],
 ['FORWARD, REVERSE, LEFT & RIGHT','Grid','Forward/reverse: full grid steps. Left/right: 90° turns on the spot. Test mode using CLEAR → Forward → Right → GO.'],
 ['Switch Grid / Draw Mode','Modes','Press ACTION + REVERSE together. Purple indicates Draw Mode. Sources conflict on the Grid LED: orange in the overview, blue after toggling in some instructions. Verify by movement.'],
 ['45° and 30° turns','Draw','45°: FORWARD + LEFT/RIGHT together. 30°: REVERSE + LEFT/RIGHT together. Enter commands, then GO.'],
 ['Small & wide arcs','Draw','Hold LEFT/RIGHT for 1 second (short chime) for a small arc; 3 seconds (double chime) for a wide arc. Four small right arcs make the manual’s circle.'],
 ['Continuous forward','Draw','Hold FORWARD for 2 seconds until a buzzer, then GO. On the real robot this is continuous movement. Use clear space and be ready to switch power off. Not available in the simulator.'],
 ['Repeat a sequence','Loop','CLEAR → REPEAT once → record the commands → REPEAT for the repetition count → GO. Example: Forward → Right repeated four times makes a square.'],
 ['L, T & zigzag','Paths','L: Forward → Left → Forward. T: Forward twice → Reverse → Right → Forward twice. The workbook extends the stored L sequence with Right → Forward for its zigzag example. GO executes the full stored sequence.'],
 ['Line following & task interruption','Sensors','Long-press INTERRUPT until the buzzer, place on a suitable black track, then GO. Task interruption responds to a detected black strip with an urgent task, then resumes. Use the device’s track guide for that sequence.'],
 ['Claw & picture cards','Accessories','Fold the claw along marked lines; align tabs at the front LED holes and secure with a rubber band. Picture cards can sit in the robot’s top slot or the arena slot.'],
 ['Bluetooth & Junior Blocks','Picto','Choose Picto-Coding on the switch (blue LED), enable Bluetooth, select Board → Wizbot Maxx and the unique robot ID. A chime confirms pairing.'],
 ['Visual blocks','Picto','Build movement, Set LED / LED off, Play Sound, Stop Robot and repeat blocks. Select Grid or Draw in the Wizbot interface. Execute with the app’s green flag / Run control.'],
 ['Step calibration','Calibration','Draw Mode → align wheels → ACTION + FORWARD. LEFT shortens, RIGHT lengthens; FORWARD tests again. GO saves forward/reverse calibration.'],
 ['Left / right turn calibration','Calibration','ACTION + LEFT/RIGHT. FORWARD increases angle, REVERSE decreases angle. Test with the selected turn button; GO saves.'],
 ['IR sensor calibration','Calibration','On the actual IR black-and-white track, align wheels to the white guideline. INTERRUPT + ACTION starts forward–reverse–forward sampling. Junior Blocks also offers Calibrate IR through the line-following extension.'],
 ['Motion time in the app','Calibration','Connect in Junior Blocks. Board → Settings → Calibrate Motion Time. Select movement, change milliseconds, then Set. Compare each change on the same surface.'],
 ['LED status','Troubleshooting','Orange: button/grid operation in the overview. Purple: Draw. Blue: Picto/Bluetooth and, in some source instructions, toggled Grid. Red: low battery or calibration. Check switch position and recent actions.']
];
function renderReference(){const query=$('search').value.trim().toLowerCase();const matches=reference.filter(r=>r.join(' ').toLowerCase().includes(query));$('reference-list').innerHTML=matches.length?matches.map(r=>`<details ${query?'open':''}><summary>${r[0]} <span>${r[1]}</span></summary><p>${r[2]}</p></details>`).join(''):'<p class="empty">No matching commands. Try a different word.</p>';}
$('search').addEventListener('input',renderReference);
showLesson(current);resetPose();renderQueue();renderReference();
if(location.hash==='#advanced')requestAnimationFrame(()=>$('advanced').scrollIntoView());
